### ISSUE TITLE
 Failed to clone git@github.com:laravel/spark.git via git

### ISSUE THREAD

**Issue by hopewise** [GeneaLabs/laravel-sparkinstaller#6]
If I try to install it, I get this error:

```
 [RuntimeException]
  Failed to clone git@github.com:laravel/spark.git via git, https, ssh protocols, aborting.
  - git://github.com/laravel/spark.git
    Cloning into '/share/vendor/laravel/spark'...
    fatal: remote error:
      Repository not found.
  - https://github.com/laravel/spark.git
    Cloning into '/share/vendor/laravel/spark'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/laravel/spark.git/'
  - git@github.com:laravel/spark.git
    Cloning into '/share/vendor/laravel/spark'...
    Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

```

Any idea?

**Comment by mikebronner** [comment]
This package is currently on hiatus, until spark is released. It only worked for the v0.1.x of Spark, and too much underlying change was being made to keep this plugin up-to-date. Sorry for the inconvenience. Your best bet right now is to wait until Spark is officially released.

**Comment by hopewise** [comment]
Thanks Mike, is there an expected date? as far as I knew, that it has team
management feature, right?

On Sun, Feb 28, 2016 at 5:03 PM, Mike Bronner <notifications@github.com>
wrote:

> This package is currently on hiatus, until spark is released. It only
> worked for the v0.1.x of Spark, and too much underlying change was being
> made to keep this plugin up-to-date. Sorry for the inconvenience. Your best
> bet right now is to wait until Spark is officially released.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeneaLabs/laravel-sparkinstaller/issues/6#issuecomment-189888288>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by mikebronner** [comment]
Yes, if previous Spark pre-releases are any indication, it will allow team management and billing. :) Unfortunately no release date. Keep an eye out on twitter for #SparkWatch. :)

**Comment by hopewise** [comment]
Cool :) I will be waiting

On Sun, Feb 28, 2016 at 5:06 PM, Mike Bronner <notifications@github.com>
wrote:

> Yes, if previous Spark pre-releases are any indication, it will allow team
> management and billing. :) Unfortunately no release date. Keep an eye out
> on twitter for #SparkWatch. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeneaLabs/laravel-sparkinstaller/issues/6#issuecomment-189888968>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by canfone** [comment]
Hello, any updates regarding this question? I am experiencing it today also.

**Comment by mikebronner** [comment]
Sorry to say this package is no longer applicable to the current version of Spark. (It worked for the initial beta package that was free.)
